# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: kong
      image: docker.io/bitnami/kong:3.6.0-debian-12-r0
    - name: kong-ingress-controller
      image: docker.io/bitnami/kong-ingress-controller:3.1.0-debian-12-r4
    - name: postgresql
      image: docker.io/bitnami/postgresql:14.11.0-debian-12-r6
apiVersion: v2
appVersion: 3.6.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 10.x.x
description: Kong is an open source Microservice API gateway and platform designed for managing microservices requests of high-availability, fault-tolerance, and distributed systems.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kong/img/kong-stack-220x234.png
keywords:
- kong
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: kong
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kong
version: 10.7.1
